name: "whatup"
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "0.1.0"
usage: "checks if installed charts are out of date"
description: "Checks if installed charts are out of date against the Helm repositories."
command: "$HELM_PLUGIN_DIR/whatup.sh"
useTunnel: true
